---
# We need sudo for some of the Docker commands.
sudo: required

env:
  # Provide a list of OSes we want to use for testing.
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: fedora25
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: debian8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

before_install:
  # Pull container from Docker Hub.
  - 'docker pull chrisshort/docker-${distro}-ansible:latest'

script:
  # Start the container from the image and perform tests.
  
  # Create a random file to store the container ID.
  - container_id=$(mktemp)

  # Run container detached, with our role mounted inside.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-role-papertrail:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  # Check the role/playbook's syntax.
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/ansible/roles/ansible-role-papertrail/tests/test.yml
    --syntax-check

  # Run the role/playbook with ansible-playbook.
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/ansible/roles/ansible-role-papertrail/tests/test.yml

  # Run the role/playbook again, checking to make sure it's idempotent.
  - idempotence=$(mktemp)
  - >
    docker exec "$(cat ${container_id})"
    ansible-playbook /etc/ansible/roles/ansible-role-papertrail/tests/test.yml
    | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Ensure remote_syslog is installed.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm which remote_syslog'

  # Stat files.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm stat /etc/log_files.yml /etc/ssl/certs/papertrail-bundle.pem /etc/rsyslog.d/papertrail.conf /usr/local/bin/remote_syslog'

  # Ensure rsyslog.service is running.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l status rsyslog'

  # Ensure remote_syslog.service is running.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l is-enabled remote_syslog'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

slack:
  secure: FlqJDbBKnn8X+qVEiTlDe8GRP51pWfxXlNnuCoQGoACB5RoAUff1KTWVYB/GNi2QL3eeb2zN0IlAuECjZyytjNXs1tR4Vmj+SazFc/si0LGgqKeeQb0x1Xab0tQ7LfJheYW02pGicbXGaX5kdzd624Hkg9tLMKnisJmLjVzGW3GFfH2QVnPLnV0lnwSu5JPKDYK5qhV9+oQKupdFBVBo9ghpF6za3kxT6DLlcsgTXCaz51G1W30mNH6Jf5xTNq/y7nwaDyydhaDuwidCvrssLaNxgm55qbzpihDpHG91UGsQ2wcrFnChcibKah0Z/KTtGTCosTQ6JbIDx1HGOQBMyuueu+5f82gsYpiOjW7OZBinkxnWhnIxK5LrQws6y5kQ4bSP5to77K8nJSRW6gP6FuYftDX0HkCFlQkHBpLx7HY+9wMvc8kYi395UBOTrT//lINn9t0tWDIBPSdediWgMIUuOfA6jMmJ5NpZ5Zmr6cgz6Jk8Rawh+APPf2oIOQNcqTbxyOZj/NPIqqeBlJUReBqh/ucLtc7+PDixL3g0ie+6Uj9MMWyLkTLyqTsk+yI3uK7bl0slwqg9EOn5mffKL92Dj3k2huzjiK4NzwBVejSNQHyo8KZ3PgDOo3VDVfn5x3ABaSeomukDlZxVZQMF43eBttEWE9VtIPb1e8N76gs=
