---
- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: daemon-reload
  shell: systemctl daemon-reload

- name: enable remote_syslog
  service:
    name: remote_syslog.service
    enabled: yes

- name: restart remote_syslog
  service:
    name: remote_syslog.service
    state: restarted

- name: enable remote_syslog.init.d
  service:
    name: remote_syslog
    state: enabled

- name: restart remote_syslog.init.d
  service:
    name: remote_syslog
    state: restarted
