---
- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: daemon-reload
  shell: systemctl daemon-reload

- name: enable remote syslog
  service: name=remote_syslog.service enabled=yes state=started
